### ISSUE TITLE
Another Dataset

### ISSUE THREAD

**Issue by artiransaygin** [zhangzhao156/Human-Activity-Recognition-Codes-Datasets#2]
Hi,

First of all, thanks for sharing the code for your amazing work. My question is, can I test the U-Net architecture on a dataset I created? If yes, how? Thanks!

**Comment by zhangzhao156** [comment]
Of course, you can use your own dataset, but it's best if your dataset contains the labels of all the timestamples in order to make dense predictions. You can write your own load_dataset function as the other datasets do in unet_data_load.py
